table dim_date
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: date_key

	column date
		dataType: dateTime
		isKey
		formatString: dd-mmm-yyyy
		summarizeBy: none
		sourceColumn: date

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column quarter
		dataType: int64
		summarizeBy: none
		sourceColumn: quarter

	column month
		dataType: int64
		summarizeBy: none
		sourceColumn: month

	column month_name
		dataType: string
		sortByColumn: month
		summarizeBy: none
		sourceColumn: month_name

	column year_month
		dataType: string
		summarizeBy: none
		sourceColumn: year_month

	column is_weekend
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_weekend

	column fiscal_year
		dataType: int64
		summarizeBy: none
		sourceColumn: fiscal_year

	hierarchy Calendar

		level year
			column: year

		level quarter
			column: quarter

		level month_name
			column: month_name

		level date
			column: date

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"month", Int64.Type}, {"month_name", text}, {"year_month", text}, {"is_weekend", type logical}, {"fiscal_year", Int64.Type}}, "en-US")
				in
				    Typed

