table dim_customer

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id

	column segment
		dataType: string
		summarizeBy: none
		sourceColumn: segment

	column signup_date
		dataType: dateTime
		formatString: dd-mmm-yyyy
		summarizeBy: none
		sourceColumn: signup_date

	column customer_key
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: customer_key

	partition dim_customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_customer.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"customer_id", text}, {"segment", text}, {"signup_date", type date}, {"customer_key", Int64.Type}}, "en-US")
				in
				    Typed

